version: "3"
services:
  web:
    build: ./web/
    container_name: vue_frontend
    ports:
      - 8080:8080
    environment:
      - BACKEND_URL=http://localhost:3000
    links:
      - rails
    depends_on:
      - rails
  rails:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:migrate  && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: rails_backend
    ports:
      - 3000:3000
    volumes:
      - .:/myapp
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - meu_projeto_rails_data:/var/lib/postgresql/data
volumes:
  meu_projeto_rails_data:
